"init vimplug
source ~/.dotfile/nvim/plugins.vim
"init config
source ~/.dotfile/nvim/config.vim
"nvim maping
source ~/.dotfile/nvim/nvim_mapping.vim
"init lightline
source ~/.dotfile/nvim/lightline.vim
"init coc_mapping
source ~/.dotfile/nvim/coc_mapping.vim
