"init vimplug
source ~/.config/nvim/plugins.vim
"init config
source ~/.config/nvim/config.vim
"init term
source ~/.config/nvim/term.vim
"nvim maping
source ~/.config/nvim/nvim_mapping.vim
"init lightline
source ~/.config/nvim/lightline.vim
"init coc_mapping
source ~/.config/nvim/coc_mapping.vim
